name: medication_reminder_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2
  google_mlkit_barcode_scanning: ^0.14.1
  flutter_secure_storage: ^9.2.4 
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^19.4.0 
  timezone: ^0.10.1        
  fl_chart: ^1.0.0
  internet_connection_checker_plus: ^2.7.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:  
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

#  การตั้งค่าเปลี่ยน App Icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon.png"  # ไฟล์ไอคอนของคุณ
  min_sdk_android: 21

flutter:
  uses-material-design: true
